import "./globals.css";
import { Sidebar } from "@/ui/Sidebar";
import Card from "@/ui/Card";
import Navbar from "@/ui/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="sm:flex sm:p-6">
        <Sidebar />
        <main className="sm:w-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
